sonar.projectKey=django-project
sonar.projectName=CAEL Django Project
sonar.projectVersion=1.0

# irectorios a analizar
sonar.sources=core,micsv,frontend

# Exclusiones
sonar.exclusions=**/migrations/**, **/__pycache__/**, **/static/**, **/venv/**, **/tests_selenium/**

# Tests
sonar.tests=tests_selenium
sonar.test.inclusions=tests_selenium/**/*.py, core/settings_test.py

sonar.sourceEncoding=UTF-8

# URL servidor SonarQube
sonar.host.url=http://host.docker.internal:9000