# Generated by Django 5.2.8 on 2025-11-15 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('svGestionRegistros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroBase',
            fields=[
                ('id_reg_base', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_entrada', models.DateTimeField()),
                ('fecha_hora_salida', models.DateTimeField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='svGestionRegistros.alumno')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='svGestionRegistros.maquina')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroLibre',
            fields=[
                ('reg_base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='libre', serialize=False, to='svRegAcceso.registrobase')),
                ('motivo', models.CharField(choices=[('correo', 'Revisar correo'), ('proyecto', 'Proyecto'), ('trabajo', 'Trabajo'), ('extra', 'Extra clase'), ('otro', 'Otro')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroClase',
            fields=[
                ('reg_base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='clase', serialize=False, to='svRegAcceso.registrobase')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='svGestionRegistros.asignatura')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='svGestionRegistros.profesor')),
            ],
        ),
    ]
