# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFtestaccesoLibreNormal():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_ftestaccesoLibreNormal(self):
    print("`set speed` is a no-op in code export, use `pause` instead")
    self.driver.get("http://localhost:8000/acceso/registro/libre")
    self.driver.set_window_size(1112, 867)
    self.driver.find_element(By.ID, "codigoAlumno").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "codigoAlumno").send_keys("2010766")
    time.sleep(1)
    self.driver.find_element(By.ID, "maquina").click()
    time.sleep(1)
    dropdown = self.driver.find_element(By.ID, "maquina")
    time.sleep(1)
    dropdown.find_element(By.XPATH, "//option[. = 'LAB-01']").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#maquina > option:nth-child(2)").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "motivo").click()
    time.sleep(1)
    dropdown = self.driver.find_element(By.ID, "motivo")
    time.sleep(1)
    dropdown.find_element(By.XPATH, "//option[. = 'Revisar correo']").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#motivo > option:nth-child(2)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    time.sleep(1)
    assert self.driver.find_element(By.ID, "mensajeLibre").text == "Entrada libre registrada correctamente."
  
