# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFtestregistro3MaquinasBorrar():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_ftestregistro3MaquinasBorrar(self):
    print("`set speed` is a no-op in code export, use `pause` instead")
    self.driver.get("http://localhost:8000/gestion/maquinas")
    self.driver.set_window_size(1112, 867)
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(31) .btn-delete").click()
    time.sleep(1)
    assert self.driver.switch_to.alert.text == "¿Eliminar máquina?"
    time.sleep(1)
    self.driver.switch_to.alert.accept()
  
