# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFtestaccesoSalida2():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_ftestaccesoSalida2(self):
    print("`set speed` is a no-op in code export, use `pause` instead")
    self.driver.get("http://localhost:8000/acceso/registro/salida")
    self.driver.set_window_size(1112, 867)
    self.driver.find_element(By.ID, "codigoAlumnoSalida").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "codigoAlumnoSalida").send_keys("2010766")
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    time.sleep(1)
    assert self.driver.find_element(By.ID, "mensajeSalida").text == "Salida registrada correctamente."
  
