# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

def get_remote_firefox():
    options = Options()
    options.add_argument("--headless")  # opcional, recomendable para CI

    return webdriver.Remote(
        command_executor="http://selenium-hub:4444/wd/hub",
        options=options,
        desired_capabilities=DesiredCapabilities.FIREFOX
    )

class TestFtestregistro2ProfesoresEditar():
  def setup_method(self, method):
    self.driver = get_remote_firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_ftestregistro2ProfesoresEditar(self):
    print("`set speed` is a no-op in code export, use `pause` instead")
    self.driver.get("http://cael-test:8000/gestion/profesores")
    self.driver.set_window_size(1112, 867)
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(11) .btn-edit").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "nombre").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "nombre").send_keys("Prueba2")
    time.sleep(1)
    self.driver.find_element(By.ID, "apellido").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "apellido").send_keys("Prueba2")
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary:nth-child(1)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(11) .btn-edit").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "nombre").click()
    self.driver.find_element(By.ID, "nombre").clear()
    time.sleep(1)
    self.driver.find_element(By.ID, "nombre").send_keys("Prueba")
    time.sleep(1)
    self.driver.find_element(By.ID, "apellido").click()
    self.driver.find_element(By.ID, "apellido").clear()
    time.sleep(1)
    self.driver.find_element(By.ID, "apellido").send_keys("Prueba")
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary:nth-child(1)").click()
  
