# Generated by Django 5.2.8 on 2025-11-15 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id_maquina', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id_profesor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_alumno', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('carrera', models.CharField(max_length=100)),
                ('ciclo', models.PositiveSmallIntegerField()),
                ('fecha_nacimiento', models.DateField()),
            ],
            options={
                'indexes': [models.Index(fields=['codigo_alumno'], name='svGestionRe_codigo__1582ed_idx')],
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id_asignatura', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaturas', to='svGestionRegistros.profesor')),
            ],
        ),
    ]
